// GENERATED by scripts/build_splash_scene.py. Do not edit by hand.

/// Size of the designer's canvas every offset below refers to.
const splashSceneWidth = 941.0;
const splashSceneHeight = 1672.0;

/// Scene layers back to front: asset name and top-left offset.
const splashSceneLayers = <({String name, double left, double top})>[
  (name: 'clouds', left: 0.0, top: 871.0),
  (name: 'sun', left: 146.0, top: 1126.0),
  (name: 'landscape', left: 0.0, top: 960.0),
  (name: 'tourists', left: 811.0, top: 1312.0),
];
