#!/usr/bin/env python3
"""Build the preloader scene from the designer's layers.

  python3 scripts/build_splash_scene.py /path/to/preloader/layers

The layers are one consistent scene (unlike the four day-part pictures, whose
mountains and coast sit in different places, which made the old cross-fade
jump). This script:

* crops every layer to its content and writes it to assets/splash/scene/;
* shrinks the sky (a plain gradient) to a thin strip, scaled back up at run
  time;
* composites the finished day scene (without the logo) into
  assets/splash/scene_day.jpg for the welcome screen and reduce-motion;
* writes lib/core/startup/splash_scene_layout.dart with each layer's offset.

Layer 9 (the raster logo) is skipped: the app draws the vector logo.
Needs Pillow.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets/splash/scene"
NAMES = {
    2: "clouds",
    3: "sun",
    4: "sea",
    5: "mountains",
    6: "coast",
    7: "foreground",
    8: "tourists",
    10: "gull",
}


def number(path: Path) -> int:
    return int(path.name.split("(")[1].split(")")[0])


def main() -> None:
    layers_dir = Path(sys.argv[1])
    files = {number(p): p for p in layers_dir.glob("*.png")}
    OUT.mkdir(parents=True, exist_ok=True)

    sky = Image.open(files[1]).convert("RGB")
    size = sky.size
    sky.resize((16, 418), Image.LANCZOS).save(OUT / "sky_day.png")

    composite = sky.convert("RGBA")
    entries = []
    for index, name in NAMES.items():
        layer = Image.open(files[index]).convert("RGBA")
        assert layer.size == size, (index, layer.size)
        bbox = layer.getchannel("A").point(lambda a: 255 if a > 2 else 0).getbbox()
        cropped = layer.crop(bbox)
        cropped.save(OUT / f"{name}.png", optimize=True)
        composite.alpha_composite(layer)
        entries.append((name, bbox[0], bbox[1]))

    composite.convert("RGB").save(ROOT / "assets/splash/scene_day.jpg", quality=88)

    lines = [
        "// GENERATED by scripts/build_splash_scene.py. Do not edit by hand.",
        "",
        "/// Size of the designer's canvas every offset below refers to.",
        f"const splashSceneWidth = {size[0]}.0;",
        f"const splashSceneHeight = {size[1]}.0;",
        "",
        "/// Scene layers back to front: asset name and top-left offset.",
        "const splashSceneLayers = <({String name, double left, double top})>[",
    ]
    for name, left, top in entries:
        lines.append(f"  (name: '{name}', left: {left}.0, top: {top}.0),")
    lines.append("];")
    (ROOT / "lib/core/startup/splash_scene_layout.dart").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
